# Generated by Django 4.2.5 on 2024-02-05 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "userauths",
            "0013_remove_predio_departamento_remove_predio_distrito_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
