# Generated by Django 4.2.5 on 2024-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0014_remove_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
