# Generated by Django 4.2.5 on 2024-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0015_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
