# Generated by Django 4.2.5 on 2024-02-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0016_profile_username_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
