# Generated by Django 4.2.5 on 2024-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0017_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
