# Generated by Django 4.2.5 on 2024-02-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0020_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="predio",
            name="departamento",
            field=models.CharField(default="No disponible", max_length=500),
        ),
        migrations.AddField(
            model_name="predio",
            name="distrito",
            field=models.CharField(default="No disponible", max_length=500),
        ),
        migrations.AddField(
            model_name="predio",
            name="provincia",
            field=models.CharField(default="No disponible", max_length=500),
        ),
        migrations.AddField(
            model_name="predio",
            name="zona",
            field=models.CharField(
                blank=True, default="No disponible", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="static/default.png", null=True, upload_to="users/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
