# Generated by Django 4.2.5 on 2024-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userauths",
            "0021_predio_departamento_predio_distrito_predio_provincia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="predio",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predio",
            name="tamaño_propiedad",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
