# Generated by Django 4.2.5 on 2024-02-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0022_predio_descripcion_predio_tamaño_propiedad"),
    ]

    operations = [
        migrations.AddField(
            model_name="deuda",
            name="fecha_vencimiento",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
