# Generated by Django 4.2.5 on 2024-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0023_deuda_fecha_vencimiento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deuda",
            name="deuda",
        ),
        migrations.AddField(
            model_name="deuda",
            name="detalles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deuda",
            name="tipo_deuda",
            field=models.CharField(
                choices=[
                    ("Impuestos", "Inpuestos"),
                    ("Servicios", "Servicios"),
                    ("Cuotas", "Cuotas"),
                    ("Otros", "Otros"),
                ],
                default="Impuestos",
                max_length=20,
            ),
        ),
    ]
