# Generated by Django 4.2.5 on 2024-02-14 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0024_remove_deuda_deuda_deuda_detalles_deuda_tipo_deuda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deuda",
            name="fecha_vencimiento",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
