# Generated by Django 4.2.5 on 2024-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0025_alter_deuda_fecha_vencimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="construccion",
            name="estado_construccion",
            field=models.CharField(
                choices=[
                    ("Nuevo", "Nuevo"),
                    ("Usado", "Usado"),
                    ("Remodelación", "Remodelación"),
                    ("Otro", "Otro"),
                ],
                default="Nuevo",
                max_length=20,
            ),
        ),
    ]
